In [50]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

In [51]:
iris = load_iris()

In [52]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2)

In [53]:
lr = LinearRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9186469676077574

In [54]:
log = LogisticRegression(max_iter=1000)
log.fit(x_train, y_train)
log.score(x_test, y_test)

0.9333333333333333

In [55]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9666666666666667

In [56]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9333333333333333

In [57]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [58]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [59]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [60]:
get_score(LogisticRegression(max_iter=1000), x_train, x_test, y_train, y_test)

0.9333333333333333

In [70]:
import numpy as np

In [73]:
from sklearn.model_selection import cross_val_score
score_lr = cross_val_score(LinearRegression(), iris.data, iris.target)
score_lr

array([0.        , 0.85124923, 0.        , 0.76155439, 0.        ])

In [74]:
np.average(score_lr)

0.32256072489000853

In [75]:
from sklearn.model_selection import cross_val_score
score_svm = cross_val_score(SVC(), iris.data, iris.target)
score_svm

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [76]:
np.average(score_svm)

0.9666666666666666

In [78]:
from sklearn.model_selection import cross_val_score
score_log = cross_val_score(LogisticRegression(max_iter=1000), iris.data, iris.target)
score_log

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [79]:
np.average(score_log)

0.9733333333333334

In [90]:
from sklearn.model_selection import cross_val_score
score_rf = cross_val_score(RandomForestClassifier(n_estimators=65), iris.data, iris.target)
score_rf

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [91]:
np.average(score_rf)

0.9600000000000002

## Score max is get from LogisticRegression as 0.9733..